language: ruby
rvm:
  - 2.2.1
git:
  submodules: false
env:
  global:
    - RACK_ENV=test
    - CODACY_PROJECT_TOKEN=588960f66458422cacbbf1898db79954
notifications:
  email:
    recipients:
      - wordman05@gmail.com
    on_success: change
    on_failure: always
branches:
  only:
  - master
install:
  - bundle install
script:
  - rake test --trace
#deploy:
#  provider: heroku
#  api_key: "9951e24c-b489-48fe-8a60-b325e8d850dd"
#  app: ldsyouth-notify
#  skip_cleanup: true
